name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push CMake image to Docker Hub
    runs-on: ubuntu-latest
    env:
      CMAKE_VER: 3.23.2
    steps:
      - name: Checks out the repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push CMake v${{ env.CMAKE_VER }} Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            esmundosu/build.cmake:v${{ env.CMAKE_VER }}
            esmundosu/build.cmake:latest
          build-args: CMAKE_VER=${{ env.CMAKE_VER }}